### PR TITLE
fix error: EADDRINUSE: Address already in use #6

### PR DESCRIPTION
**Pull request by deftsp**

### CODE REVIEW

**Comment by ekzhang** [comment]
What is the status of this?

**Comment by deftsp** [comment]
Status?  The EADDRINUSE problem no longer bother me anyway.

**Comment by ekzhang** [comment]
I am experiencing the same issue right now. How did you fix the EADDRINUSE error?

**Comment by deftsp** [comment]
Here, https://github.com/mitsuhiko/systemfd/pull/10/files#diff-63d778a2971dfb2e16dbf22e6dc60deaR152

**Comment by ekzhang** [comment]
Is it possible for this fix to be merged in?

@mitsuhiko

**Comment by cortopy** [comment]
@mitsuhiko would you mind commenting if this PR has any chance of getting merged at some point?

**Pull request merged**
